### ISSUE TITLE
Declaring special vars to be special seems redundant and violates package locks on SBCL

### ISSUE THREAD

**Issue by digikar99** [alex-gutev/cl-environments#13] opened 2023-11-30 08:17 UTC
https://github.com/alex-gutev/cl-environments/blob/1bd7ecf68adeaf654616c6fb763c1239e0f2e221/src/other/sbcl.lisp#L213-L214

Is there a reason why vars that are already special are being declared special?

Currently, the above leads to an error on the following. But not appending the special declaration fixes the issue.

```lisp
CL-FORM-TYPES> (cl-form-types:nth-form-type `(handler-bind ((error (lambda (c)
                                                                     (print c))))
                                               (fun))
                                            nil)
; Evaluation aborted on #<SB-KERNEL:CASE-FAILURE expected-type: (MEMBER :COMPILE :EVAL) datum: NIL>.
```

```lisp
NIL fell through ECASE expression.
Wanted one of (:COMPILE :EVAL).
   [Condition of type SB-KERNEL:CASE-FAILURE]

Restarts:
 0: [IGNORE-ALL] Ignore all package locks in the context of this operation.
 1: [UNLOCK-PACKAGE] Unlock the package.
 2: [RETURN-DEFAULT-TYPE] RETURN-DEFAULT-TYPE
 3: [RETRY] Retry SLIME REPL evaluation request.
 4: [*ABORT] Return to SLIME's top level.
 5: [ABORT] abort thread (#<THREAD tid=51785 "repl-thread" RUNNING {10014700A3}>)

Backtrace:
  0: ((LAMBDA (CONDITION) :IN SB-KERNEL:PROGRAM-ASSERT-SYMBOL-HOME-PACKAGE-UNLOCKED) #<SB-EXT:SYMBOL-PACKAGE-LOCKED-ERROR "declaring ~A special" {100FB6F2B3}>)
  1: (SB-KERNEL::%SIGNAL #<SB-EXT:SYMBOL-PACKAGE-LOCKED-ERROR "declaring ~A special" {100FB6F2B3}>)
  2: (CERROR "Ignore the package lock." SB-EXT:SYMBOL-PACKAGE-LOCKED-ERROR :PACKAGE #<PACKAGE "SB-KERNEL"> :FORMAT-CONTROL "declaring ~A special" :FORMAT-ARGUMENTS (SB-KERNEL:*HANDLER-CLUSTERS*) :SYMBOL SB..
  3: (SB-EXT:PACKAGE-LOCK-VIOLATION #<PACKAGE "SB-KERNEL"> :SYMBOL SB-KERNEL:*HANDLER-CLUSTERS* :FORMAT-CONTROL "declaring ~A special" :FORMAT-ARGUMENTS (SB-KERNEL:*HANDLER-CLUSTERS*))
  4: (SB-KERNEL:ASSERT-SYMBOL-HOME-PACKAGE-UNLOCKED SB-KERNEL:*HANDLER-CLUSTERS* "declaring ~A special")
  5: (SB-KERNEL:PROGRAM-ASSERT-SYMBOL-HOME-PACKAGE-UNLOCKED NIL SB-KERNEL:*HANDLER-CLUSTERS* "declaring ~A special")
  6: (SB-C::PROCESS-1-DECL (SPECIAL SB-KERNEL:*HANDLER-CLUSTERS*) #<SB-KERNEL:LEXENV {100FB6F0F3}> (#<SB-C::LAMBDA-VAR :%SOURCE-NAME SB-KERNEL:*HANDLER-CLUSTERS* {100FB6F173}>) NIL NIL NIL)
  7: ((FLET SB-C::PROCESS-IT :IN SB-C::PROCESS-DECLS) (SPECIAL SB-KERNEL:*HANDLER-CLUSTERS*) (DECLARE (SPECIAL SB-KERNEL:*HANDLER-CLUSTERS*) (DYNAMIC-EXTENT SB-KERNEL:*HANDLER-CLUSTERS*)))
  8: (SB-C::PROCESS-DECLS ((DECLARE (SPECIAL SB-KERNEL:*HANDLER-CLUSTERS*) (DYNAMIC-EXTENT SB-KERNEL:*HANDLER-CLUSTERS*))) (#<SB-C::LAMBDA-VAR :%SOURCE-NAME SB-KERNEL:*HANDLER-CLUSTERS* {100FB6F173}>) NIL ..
  9: (SB-CLTL2:AUGMENT-ENVIRONMENT #<unavailable argument> :VARIABLE (SB-KERNEL:*HANDLER-CLUSTERS*) :SYMBOL-MACRO NIL :FUNCTION NIL :MACRO NIL :DECLARE ((SPECIAL SB-KERNEL:*HANDLER-CLUSTERS*) (DYNAMIC-EXTE..
 10: (LET-FORM-TYPE (((SB-KERNEL:*HANDLER-CLUSTERS* #)) (DECLARE (DYNAMIC-EXTENT SB-KERNEL:*HANDLER-CLUSTERS*)) (PROGN (FUN))) NIL)
```

**Comment by alex-gutev** [comment] 2023-12-01 07:00
I added it there because at the time SBCL's `augment-environment` seemed to "forget" special declarations. That is if a variable `x` is declared special, by `(declare (special x))` in an environment, and that environment is then augmented by `augment-environment`, the variable `x` is no a longer variable special in the environment returned by `augment-environment`, unless it is declared special in the global environment by `defvar`/`defparameter`. It seems this has been fixed in recent versions.

```lisp
(macrolet ((test (var &environment env)
		      (let ((aug-env (sb-cltl2:augment-environment env :variable '(y))))
			`'(,(sb-cltl2:variable-information var env)
			   ,(sb-cltl2:variable-information var aug-env)))))
	   (let ((x 1))
	     (declare (special x))
	     (test x)))
````

In previous versions of SBCL this evaluated to the following:

````lisp
(:SPECIAL :LEXICAL)
````

In the most recent version it evaluates to

````lisp
(:SPECIAL :SPECIAL)
````

as expected.

I believe this part of redeclaring variables as special can now be removed.

**Comment by alex-gutev** [comment] 2023-12-01 07:38
After removing the redeclaration of special variables the test case `augment-augmented-declaration` in `test/augment-environment.lisp` fails. I narrowed down the cause of the test failing to the following:

https://github.com/alex-gutev/cl-environments/blob/1bd7ecf68adeaf654616c6fb763c1239e0f2e221/src/other/sbcl.lisp#L200-L207

What I'm doing here is extracting the list of variables which are mentioned in the declarations passed to the `:declare` argument and passing those, along with all the variables passed in `:variable` to the `:variable` argument of `augment-environment`. The reason I'm doing this is that if a variable is mentioned in a declaration in `:declare` but does not appear in the list passed to the `:variable` argument of the corresponding call to `augment-declaration` a warning is emitted. More so the declaration information is not saved in the new environment:

e.g.

```lisp
(macrolet ((test (var &environment env)
		      (let ((aug-env (sb-cltl2:augment-environment env :declare '((type integer x)))))
			`'(,(multiple-value-list (sb-cltl2:variable-information var env))
			   ,(multiple-value-list (sb-cltl2:variable-information var aug-env))))))
	   (let ((x 1))
	     (declare (special x))
	     (test x)))
````

results in

````lisp
((:SPECIAL NIL NIL) (:SPECIAL NIL NIL))
````

when it should result in (ignoring the second return value which should be `T` in both cases but SBCL always returns `NIL` for special variables):

````lisp
((:SPECIAL NIL NIL) (:SPECIAL NIL ((type . integer))
````

A declaration bound to a variable which is not introduced by the environment containing the declaration can occur in `locally` forms:

````lisp
CL-USER> (macrolet ((test (var &environment env)
		      `',(multiple-value-list (sb-cltl2:variable-information var env))))
	   (let ((x 1))
	     (declare (special x))
	     (pprint x)
	     (locally (declare (type integer x))
	       (test x))))

1
(:SPECIAL NIL ((TYPE . INTEGER)))
````

Worse still if the variable was not found in the environment but was introduced into an environment by `augment-environment`, trying to further augment the environment with declaration information, by another call to `augment-environment` results in an error. e.g.

````lisp
(let* ((env1 (sb-cltl2:augment-environment
		nil
		:variable '(x)
		:declare '((special x)
			   (optimize (speed 3)))))

	 (env2 (sb-cltl2:augment-environment
		env1
		:declare '((type integer x)
			   (optimize (space 3) (safety 0))))))
	   'x)
````

Which results in:

````lisp
The variable SB-C::*IR1-NAMESPACE* is unbound.
   [Condition of type UNBOUND-VARIABLE]

Restarts:
 0: [CONTINUE] Retry using SB-C::*IR1-NAMESPACE*.
 1: [USE-VALUE] Use specified value.
 2: [STORE-VALUE] Set specified value and use it.
 3: [RETRY] Retry SLIME REPL evaluation request.
 4: [*ABORT] Return to SLIME's top level.
 5: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {1002369BC3}>)

Backtrace:
  0: (SB-C::FIND-FREE-VAR X)
  1: (SB-C::PROCESS-TYPE-DECL (INTEGER X) #S(SB-KERNEL:LEXENV :FUNS NIL :VARS ((X . #)) :BLOCKS NIL :TAGS NIL :TYPE-RESTRICTIONS NIL :LAMBDA NIL ...) NIL NIL)
  2: (SB-C::PROCESS-1-DECL (TYPE INTEGER X) #S(SB-KERNEL:LEXENV :FUNS NIL :VARS ((X . #)) :BLOCKS NIL :TAGS NIL :TYPE-RESTRICTIONS NIL :LAMBDA NIL ...) NIL NIL NIL NIL)
  3: ((FLET SB-C::PROCESS-IT :IN SB-C::PROCESS-DECLS) (TYPE INTEGER X) (DECLARE (TYPE INTEGER X) (OPTIMIZE (SPACE 3) (SAFETY 0))))
  4: (SB-C::PROCESS-DECLS ((DECLARE (TYPE INTEGER X) (OPTIMIZE # #))) NIL NIL :LEXENV #S(SB-KERNEL:LEXENV :FUNS NIL :VARS ((X . #)) :BLOCKS NIL :TAGS NIL :TYPE-RESTRICTIONS NIL :LAMBDA NIL ...) :BINDING-FO..
  5: (SB-CLTL2:AUGMENT-ENVIRONMENT #<unavailable argument> :VARIABLE NIL :SYMBOL-MACRO NIL :FUNCTION NIL :MACRO NIL :DECLARE ((TYPE INTEGER X) (OPTIMIZE (SPACE 3) (SAFETY 0))))
  6: ((LAMBDA ()))
  7: (SB-INT:SIMPLE-EVAL-IN-LEXENV (LET* ((ENV1 #) (ENV2 #)) (QUOTE X)) #<NULL-LEXENV>)
  8: (EVAL (LET* ((ENV1 #) (ENV2 #)) (QUOTE X)))
 --more--
````

This is covered by the same test case, which raises an error condition if I don't add all the variables mentioned in `:declare` to the list passed in the `:variable` argument to `augment-environment`. If we leave the native SBCL behaviour, which is inconsistent with CLTL2 and other implementations such as CCL, this will cause issues further down the line in [cl-form-types](https://github.com/alex-gutev/cl-form-types).

I guess we'll need a way to work around the package locks either by detecting them and disabling this logic when a variable in a locked package is involved or by failing gracefully.

**Comment by alex-gutev** [comment] 2023-12-01 08:02
It seems you've already proposed a solution to this issue before in https://github.com/alex-gutev/cl-environments/pull/10. With the pull request we no longer get this issue and all the test cases pass, so I will go ahead and merge it.

We might still get issues if SBCL or another package decides to use special variables which are not special in the global environment.

**Comment by digikar99** [comment] 2023-12-02 15:43
Thanks for the analysis! 

On SBCL 2.3.11 at least, we can test symbols to see if their packages are locked using `sb-ext:package-locked-p`.

**Comment by alex-gutev** [comment] 2023-12-02 17:28
That function exists in 2.27 (the version included with the Ubuntu distribution) as well. Anyway your push request, which I've merged into master, solves this occurrence of this issue, that is when the special variable in question is global.

**Comment by digikar99** [comment] 2023-12-02 17:41
Okay! Hopefully no one needs to use older SBCL and they should be good with the current state of things.

**Comment by alex-gutev** [comment] 2023-12-02 18:01
There are no checks for package locks currently. Your push request added a check for whether the symbol is a special variable in the global (`NIL`) environment, and if so it's not redeclared special in `AUGMENT-ENVIRONMENT`. This solves the current issue with package locks being violated since the variables involved are global special variables.

**Comment by alex-gutev** [comment] 2023-12-03 07:47
Now that I think of it there is no need to be checking for package locks since if a symbol, from a locked package, is locally declared special, it would violate the package lock anyway. So I will be closing this issue.

**Closed as completed by alex-gutev** 2023-12-03 07:47 UTC
